apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
  namespace: backstage
  labels:
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: idp-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backstage
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backstage
      annotations:
        sidecar.istio.io/inject: "false"  # Disable Istio for now
    spec:
      serviceAccountName: backstage
      containers:
      - name: backstage
        image: backstage/backstage:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 7007
          protocol: TCP
        env:
        - name: POSTGRES_HOST
          value: "127.0.0.1"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "backstage"
        - name: POSTGRES_PASSWORD
          value: "backstage"
        - name: APP_CONFIG_backend_database_client
          value: "better-sqlite3"
        - name: APP_CONFIG_backend_database_connection
          value: ":memory:"
        - name: APP_CONFIG_app_baseUrl
          value: "http://localhost:7007"
        - name: APP_CONFIG_backend_baseUrl
          value: "http://localhost:7007"
        - name: APP_CONFIG_auth_providers_guest_dangerouslyAllowOutsideDevelopment
          value: "true"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-simple-config
  namespace: backstage
data:
  app-config.yaml: |
    app:
      title: IDP Platform Portal
      baseUrl: http://localhost:7007

    organization:
      name: IDP Platform

    backend:
      baseUrl: http://localhost:7007
      listen:
        port: 7007
      database:
        client: better-sqlite3
        connection: ':memory:'

    auth:
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true

    catalog:
      rules:
        - allow: [Component, System, API, Resource, Location, User, Group]
      locations:
        - type: file
          target: /tmp/idp-catalog.yaml

  idp-catalog.yaml: |
    apiVersion: backstage.io/v1alpha1
    kind: System
    metadata:
      name: idp-platform
      title: IDP Platform
      description: Integrated Developer Platform
    spec:
      owner: platform-team
    ---
    apiVersion: backstage.io/v1alpha1
    kind: Component
    metadata:
      name: sample-web-app
      title: Sample Web App
      description: Sample nginx web application
      annotations:
        backstage.io/kubernetes-id: sample-web-app
        backstage.io/kubernetes-namespace: development
    spec:
      type: website
      lifecycle: experimental
      owner: development-team
      system: idp-platform