apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-rds
  labels:
    platform.idp/component: infrastructure
spec:
  package: xpkg.upbound.io/upbound/provider-aws-rds:v1.23.1
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: rds-localstack-config
  labels:
    platform.idp/component: infrastructure
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-localstack-creds
      key: credentials
  endpoint:
    url:
      type: Static
      static: http://host.docker.internal:4566
    hostnameImmutable: true
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_region_validation: true
  skip_requesting_account_id: true