apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-localstack
spec:
  package: xpkg.upbound.io/upbound/provider-aws:v0.47.0
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-localstack-creds
  namespace: crossplane-system
type: Opaque
data:
  credentials: |
    W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gdGVzdAphd3Nfc2VjcmV0X2FjY2Vzc19rZXkgPSB0ZXN0CnJlZ2lvbiA9IHVzLWVhc3QtMQo=
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: localstack-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-localstack-creds
      key: credentials
  endpoint:
    url:
      type: Static
      static: http://host.docker.internal:4566
    hostnameImmutable: true
  skip_credentials_validation: true
  skip_metadata_api_check: true
  skip_region_validation: true
  skip_requesting_account_id: true
  s3_use_path_style: true