app:
  title: IDP Platform Backstage
  baseUrl: http://backstage.idp.local

organization:
  name: IDP Platform Team

backend:
  baseUrl: http://backstage.idp.local
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", "http:", "https:", "http://backstage.idp.local"]
  cors:
    origin:
      - http://backstage.idp.local
      - http://localhost:3000
      - http://localhost:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ":memory:"

integrations:
  github:
    - host: github.com

proxy:

techdocs:
  builder: "local"
  generator:
    runIn: "local"
  publisher:
    type: "local"

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    # Built-in IDP platform entities
    - type: file
      target: ../../examples/entities.yaml
      rules:
        - allow: [User, Group]

    # IDP Platform catalog
    - type: file
      target: ../../examples/idp-catalog.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]

    # Organization structure
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    # IDP webapp template
    - type: file
      target: ../../examples/idp-webapp-template/template.yaml
      rules:
        - allow: [Template]
