app:
  title: IDP Platform Backstage
  baseUrl: http://backstage.idp.local

organization:
  name: IDP Platform Team

backend:
  baseUrl: http://backstage.idp.local
  listen:
    port: 7007
    host: 0.0.0.0
  csp:
    connect-src: ["'self'", "http:", "https:", "http://backstage.idp.local"]
  cors:
    origin:
      - http://backstage.idp.local
      - http://localhost:3000
      - http://localhost:7007
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl:
        require: false

integrations:
  github:
    - host: github.com

proxy:

techdocs:
  builder: "local"
  generator:
    runIn: "local"
  publisher:
    type: "local"

auth:
  environment: development
  providers:
    cognito:
      development:
        clientId: ${COGNITO_CLIENT_ID}
        clientSecret: ${COGNITO_CLIENT_SECRET}
        region: us-east-1
        userPoolId: ${COGNITO_USER_POOL_ID}
        authorizationUrl: ${COGNITO_AUTH_URL}
        tokenUrl: ${COGNITO_TOKEN_URL}
        scope: 'openid email profile'
        prompt: login
    guest:
      dangerouslyAllowOutsideDevelopment: true

scaffolder:

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, User, Group]
  locations:
    # Built-in IDP platform entities
    - type: file
      target: ../../examples/entities.yaml
      rules:
        - allow: [User, Group]

    # IDP Platform catalog
    - type: file
      target: ../../examples/idp-catalog.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]

    # Organization structure
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

    # IDP webapp template
    - type: file
      target: ../../examples/idp-webapp-template/template.yaml
      rules:
        - allow: [Template]
