---
apiVersion: v1
kind: Namespace
metadata:
  name: argo-workflows
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-workflows-s3
  namespace: argo-workflows
type: Opaque
data:
  accesskey: dGVzdA==  # test
  secretkey: dGVzdA==  # test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-cluster-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/finalizers", "workflowtemplates", "workflowtemplates/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
- apiGroups: ["argoproj.io"]
  resources: ["workflowtasksets", "workflowtasksets/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]
- apiGroups: ["argoproj.io"]
  resources: ["cronworkflows", "cronworkflows/finalizers"]
  verbs: ["get", "list", "watch", "update", "patch", "delete", "create"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["create", "get", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-workflow-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-workflow-cluster-role
subjects:
- kind: ServiceAccount
  name: argo-workflow
  namespace: argo-workflows
---
# Docker build service account with ECR access
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docker-builder
  namespace: argo-workflows
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: docker-builder-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: docker-builder-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: docker-builder-role
subjects:
- kind: ServiceAccount
  name: docker-builder
  namespace: argo-workflows