apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/ayansasmal/idp-platform
    targetRevision: HEAD
    path: applications/backstage
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/ayansasmal/idp-platform
    targetRevision: HEAD
    path: applications/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-ui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/ayansasmal/idp-platform
    targetRevision: HEAD
    path: applications/argocd
    directory:
      include: "*virtualservice*"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
