apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapplications.platform.idp
  labels:
    app.kubernetes.io/name: webapplication-crd
    app.kubernetes.io/part-of: idp-platform
spec:
  group: platform.idp
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              appName:
                type: string
                description: Name of the web application
                pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
              image:
                type: object
                properties:
                  repository:
                    type: string
                    description: Container image repository
                  tag:
                    type: string
                    description: Container image tag
                    default: "latest"
                  pullPolicy:
                    type: string
                    enum: ["Always", "IfNotPresent", "Never"]
                    default: "IfNotPresent"
                required:
                - repository
              replicas:
                type: integer
                minimum: 1
                maximum: 10
                default: 2
                description: Number of application replicas
              port:
                type: integer
                minimum: 1
                maximum: 65535
                default: 3000
                description: Application port
              environment:
                type: string
                enum: ["development", "staging", "production"]
                default: "development"
                description: Target environment
              resources:
                type: object
                properties:
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "100m"
                      memory:
                        type: string
                        default: "128Mi"
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        default: "500m"
                      memory:
                        type: string
                        default: "512Mi"
              autoscaling:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  minReplicas:
                    type: integer
                    minimum: 1
                    default: 2
                  maxReplicas:
                    type: integer
                    minimum: 1
                    default: 10
                  targetCPUUtilization:
                    type: integer
                    minimum: 1
                    maximum: 100
                    default: 70
              ingress:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  hostname:
                    type: string
                    description: Application hostname
                  tls:
                    type: boolean
                    default: true
              database:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: false
                  type:
                    type: string
                    enum: ["postgresql", "mysql", "mongodb"]
                    default: "postgresql"
                  size:
                    type: string
                    enum: ["small", "medium", "large"]
                    default: "small"
              monitoring:
                type: object
                properties:
                  enabled:
                    type: boolean
                    default: true
                  metrics:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                        default: true
                      path:
                        type: string
                        default: "/metrics"
                      port:
                        type: integer
                        default: 9090
            required:
            - appName
            - image
          status:
            type: object
            properties:
              phase:
                type: string
                enum: ["Pending", "Creating", "Ready", "Failed"]
                description: Current phase of the application
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                      enum: ["True", "False", "Unknown"]
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              deploymentReady:
                type: boolean
                description: Whether the deployment is ready
              serviceReady:
                type: boolean
                description: Whether the service is ready
              ingressReady:
                type: boolean
                description: Whether the ingress is ready
              databaseReady:
                type: boolean
                description: Whether the database is ready
              url:
                type: string
                description: Application URL
    additionalPrinterColumns:
    - name: Phase
      type: string
      jsonPath: .status.phase
    - name: Replicas
      type: integer
      jsonPath: .spec.replicas
    - name: Environment
      type: string
      jsonPath: .spec.environment
    - name: URL
      type: string
      jsonPath: .status.url
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
  scope: Namespaced
  names:
    plural: webapplications
    singular: webapplication
    kind: WebApplication
    shortNames:
    - webapp