apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: cert-manager
    component: certificates
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.13.3
    helm:
      values: |
        installCRDs: true
        global:
          leaderElection:
            namespace: cert-manager
        webhook:
          enabled: true
          hostNetwork: false
        cainjector:
          enabled: true
        startupapicheck:
          enabled: true
        prometheus:
          enabled: true
          servicemonitor:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 5