apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.41.11
    helm:
      values: |
        controller:
          workflowNamespaces:
            - argo-workflows
            - default
            - backstage
        
        server:
          enabled: true
          baseHref: /
          secure: false
          authModes:
            - server
          extraArgs:
            - --auth-mode=server
            - --access-control-allow-origin=*
          serviceType: ClusterIP
          servicePort: 2746
        
        executor:
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
        
        useDefaultArtifactRepo: false
        useStaticCredentials: true
        
        artifactRepository:
          s3:
            bucket: argo-artifacts
            endpoint: localstack:4566
            insecure: true
            accessKeySecret:
              name: argo-workflows-s3
              key: accesskey
            secretKeySecret:
              name: argo-workflows-s3
              key: secretkey
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m