apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: localstack-secretstore
  namespace: default
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-aws-creds
            key: access-key-id
          secretAccessKeySecretRef:
            name: localstack-aws-creds
            key: secret-access-key
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-creds
  namespace: default
type: Opaque
stringData:
  access-key-id: test
  secret-access-key: test
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: localstack-secretstore
    kind: SecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: idp/database/credentials
      property: username
  - secretKey: password
    remoteRef:
      key: idp/database/credentials
      property: password
  - secretKey: database
    remoteRef:
      key: idp/database/credentials
      property: database