apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: localstack-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: localstack-aws-creds
            key: access-key-id
            namespace: external-secrets-system
          secretAccessKeySecretRef:
            name: localstack-aws-creds
            key: secret-access-key
            namespace: external-secrets-system
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-aws-creds
  namespace: external-secrets-system
type: Opaque
stringData:
  access-key-id: test
  secret-access-key: test