apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-backend
  namespace: default
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: source-secret
  namespace: default
type: Opaque
stringData:
  username: "postgres"
  password: "secretpassword"
  database: "idpdb"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-config
  namespace: default
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: k8s-backend
    kind: SecretStore
  target:
    name: app-db-config
    creationPolicy: Owner
  data:
  - secretKey: db_username
    remoteRef:
      key: source-secret
      property: username
  - secretKey: db_password
    remoteRef:
      key: source-secret
      property: password
  - secretKey: db_name
    remoteRef:
      key: source-secret
      property: database