apiVersion: v1
kind: Secret
metadata:
  name: test-app-secret
  namespace: default
type: Opaque
stringData:
  database-url: "postgresql://user:pass@localhost:5432/testdb"
  api-key: "test-api-key-12345"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: test-secretstore
  namespace: default
spec:
  provider:
    kubernetes:
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets