# Monitoring Stack Configuration
# Default values for monitoring-stack chart

global:
  # IDP Platform namespace configuration
  namespace: monitoring
  domain: idp.local
  
# Prometheus Configuration
prometheus:
  enabled: true
  version: "2.49.1"
  
  server:
    persistentVolume:
      enabled: true
      size: 8Gi
      
  config:
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      
    rule_files:
      - "platform_rules.yml"
      - "application_rules.yml"
      
  alerting:
    alertmanagers:
      - static_configs:
          - targets:
            - alertmanager:9093

# Grafana Configuration            
grafana:
  enabled: true
  version: "10.2.3"
  
  admin:
    user: admin
    password: admin  # Should be overridden in production
    
  persistence:
    enabled: true
    size: 2Gi
    
  datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090
      access: proxy
      isDefault: true
      
  dashboards:
    enabled: true
    configMaps:
      - platform-overview
      - application-metrics
      - infrastructure-health
      
  plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel

# Alertmanager Configuration
alertmanager:
  enabled: true
  version: "0.26.0"
  
  config:
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'alerts@idp.local'
      
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      
    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://monitoring-webhook:5000/webhook'

# IDP Platform Integration
platform:
  integration:
    argocd: true
    backstage: true
    istio: true
    
  metrics:
    retention: "30d"
    
  alerts:
    enabled: true
    rules:
      - platform-health
      - application-sla
      - resource-utilization

# Resource Limits
resources:
  prometheus:
    requests:
      memory: 512Mi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 1000m
      
  grafana:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m
      
  alertmanager:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 200m