apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: istio-system
  labels:
    app.kubernetes.io/name: alertmanager
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'localhost:587'
      smtp_from: 'idp-platform@company.com'

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'web.hook'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
      - match:
          severity: warning
        receiver: 'warning-alerts'

    receivers:
    - name: 'web.hook'
      webhook_configs:
      - url: 'http://monitoring-dashboard.istio-system.svc.cluster.local/webhook'

    - name: 'critical-alerts'
      webhook_configs:
      - url: 'http://monitoring-dashboard.istio-system.svc.cluster.local/critical-webhook'
        send_resolved: true

    - name: 'warning-alerts'
      webhook_configs:
      - url: 'http://monitoring-dashboard.istio-system.svc.cluster.local/warning-webhook'
        send_resolved: true

    inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: istio-system
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
        - --config.file=/etc/alertmanager/alertmanager.yml
        - --storage.path=/alertmanager
        - --web.external-url=http://alertmanager.idp.local
        - --web.route-prefix=/
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: config
          mountPath: /etc/alertmanager
        - name: storage
          mountPath: /alertmanager
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config
        configMap:
          name: alertmanager-config
      - name: storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: istio-system
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  ports:
  - port: 9093
    targetPort: 9093
  selector:
    app.kubernetes.io/name: alertmanager
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: alertmanager
  namespace: istio-system
  labels:
    app.kubernetes.io/name: alertmanager
spec:
  hosts:
  - alertmanager.idp.local
  gateways:
  - istio-system/idp-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: alertmanager
        port:
          number: 9093
    timeout: 60s