apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: idp-platform-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/your-org/idp-platform
    targetRevision: HEAD
    path: applications
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: idp-platform
  namespace: argocd
spec:
  description: IDP Platform Applications
  sourceRepos:
    - "https://github.com/your-org/idp-platform"
    - "https://charts.crossplane.io/stable"
    - "https://istio-release.storage.googleapis.com/charts"
    - "https://external-secrets.github.io/external-secrets"
    - "https://charts.jetstack.io"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://grafana.github.io/helm-charts"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
