apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-web-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: sample-web-app
    platform.idp/environment: development
    platform.idp/type: web-application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ayansasmal/idp-platform
    targetRevision: HEAD
    path: applications/sample-web-app
  destination:
    server: https://kubernetes.default.svc
    namespace: development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 3
