apiVersion: v1
kind: Service
metadata:
  name: localhost-localstack-cloud
  namespace: default
  labels:
    app.kubernetes.io/name: localstack-external
    platform.idp/component: external-service
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 4566
    targetPort: 4566
    name: localstack
---
apiVersion: v1
kind: Endpoints
metadata:
  name: localstack-external
  namespace: default
subsets:
- addresses:
  - ip: 192.168.65.254  # Docker Desktop host IP
  ports:
  - port: 4566
    name: localstack
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: crossplane-system
  labels:
    app.kubernetes.io/name: localstack-crossplane
    platform.idp/component: external-service
spec:
  type: ExternalName
  externalName: host.docker.internal
  ports:
  - port: 4566
    targetPort: 4566
    name: localstack
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: localstack-external
  namespace: istio-system
spec:
  hosts:
  - localstack.external
  - localhost.localstack.cloud
  ports:
  - number: 4566
    name: http
    protocol: HTTP
  location: MESH_EXTERNAL
  resolution: DNS
  endpoints:
  - address: host.docker.internal