apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: postgresql-database
  labels:
    provider: aws
    service: rds
    database: postgresql
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: platform.idp/v1alpha1
    kind: XDatabase
  resources:
  - name: rds-subnet-group
    base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: SubnetGroup
      spec:
        providerConfigRef:
          name: localstack-config
        forProvider:
          region: us-east-1
          subnetIds:
          - subnet-12345
          - subnet-67890
          tags:
            Environment: development
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.environment
      toFieldPath: spec.forProvider.tags.Environment
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
      transforms:
      - type: string
        string:
          fmt: "%s-subnet-group"
  - name: rds-instance
    base:
      apiVersion: rds.aws.upbound.io/v1beta1
      kind: Instance
      spec:
        providerConfigRef:
          name: localstack-config
        forProvider:
          region: us-east-1
          engine: postgres
          engineVersion: "13.7"
          instanceClass: db.t3.micro
          allocatedStorage: 20
          storageType: gp2
          storageEncrypted: true
          multiAz: false
          publiclyAccessible: false
          autoMinorVersionUpgrade: true
          deletionProtection: false
          skipFinalSnapshot: true
          tags:
            ManagedBy: crossplane
        writeConnectionSecretsToRef:
          namespace: crossplane-system
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.size
      toFieldPath: spec.forProvider.instanceClass
      transforms:
      - type: map
        map:
          small: db.t3.micro
          medium: db.t3.small
          large: db.t3.medium
    - type: FromCompositeFieldPath
      fromFieldPath: spec.size
      toFieldPath: spec.forProvider.allocatedStorage
      transforms:
      - type: map
        map:
          small: 20
          medium: 100
          large: 500
    - type: FromCompositeFieldPath
      fromFieldPath: spec.dbName
      toFieldPath: spec.forProvider.dbName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.environment
      toFieldPath: spec.forProvider.tags.Environment
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.writeConnectionSecretsToRef.name
      transforms:
      - type: string
        string:
          fmt: "%s-db-connection"
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: spec.forProvider.dbSubnetGroupName
      transforms:
      - type: string
        string:
          fmt: "%s-subnet-group"
    connectionDetails:
    - fromConnectionSecretKey: username
    - fromConnectionSecretKey: password
    - fromConnectionSecretKey: endpoint
    - fromConnectionSecretKey: port
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatabases.platform.idp
spec:
  group: platform.idp
  names:
    kind: XDatabase
    plural: xdatabases
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              dbName:
                type: string
                description: Name of the database
              size:
                type: string
                enum: ["small", "medium", "large"]
                default: "small"
                description: Size of the database instance
              environment:
                type: string
                enum: ["development", "staging", "production"]
                default: "development"
                description: Environment for the database
            required:
            - dbName
          status:
            type: object
            properties:
              ready:
                type: boolean
                description: Whether the database is ready