apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: localstack-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: idp-platform
  source:
    repoURL: https://github.com/ayansasmal/idp-platform
    targetRevision: HEAD
    path: infrastructure/localstack
  destination:
    server: https://kubernetes.default.svc
    namespace: localstack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
