apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: docker-image-build
  title: Build Docker Image
  description: Build and push a Docker image to ECR using Argo Workflows
  tags:
    - docker
    - ci-cd
    - argo-workflows
spec:
  owner: platform-team
  type: workflow
  parameters:
    - title: Source Code Information
      required:
        - name
        - repoUrl
      properties:
        name:
          title: Application Name
          type: string
          description: Name of the application/image
          pattern: '^[a-z0-9-]+$'
          maxLength: 50
        description:
          title: Description
          type: string
          description: Brief description of the application
        repoUrl:
          title: Repository URL
          type: string
          description: Git repository URL containing the source code
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
              - gitlab.com
              - bitbucket.org
        branch:
          title: Branch/Tag
          type: string
          description: Git branch or tag to build from
          default: main

    - title: Build Configuration
      required:
        - dockerfile
        - buildContext
      properties:
        dockerfile:
          title: Dockerfile Path
          type: string
          description: Path to Dockerfile relative to repository root
          default: Dockerfile
        buildContext:
          title: Build Context
          type: string
          description: Docker build context path
          default: .
        imageTag:
          title: Image Tag
          type: string
          description: Docker image tag
          default: latest
          pattern: '^[a-zA-Z0-9._-]+$'
        
    - title: Target Environment
      properties:
        environment:
          title: Environment
          type: string
          description: Target deployment environment
          default: development
          enum:
            - development
            - staging
            - production

  steps:
    - id: trigger-workflow
      name: Trigger Argo Workflow
      action: argo-workflows:create
      input:
        namespace: argo-workflows
        workflowName: build-${{ parameters.name }}-${{ '' | now | date('YYYYMMDDHHmmss') }}
        workflowTemplate: docker-build-push
        parameters:
          repo-url: ${{ parameters.repoUrl }}
          revision: ${{ parameters.branch }}
          image-name: ${{ parameters.name }}
          image-tag: ${{ parameters.imageTag }}
          dockerfile-path: ${{ parameters.dockerfile }}
          build-context: ${{ parameters.buildContext }}
          ecr-registry: 000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566

    - id: register-image
      name: Register Image in Catalog
      action: catalog:register
      input:
        repoContentsUrl: ${{ parameters.repoUrl }}
        catalogInfoPath: '/catalog-info.yaml'
        optional: true

  output:
    links:
      - title: View Workflow
        url: http://localhost:4000/workflows/argo-workflows/${{ steps['trigger-workflow'].output.workflowName }}
      - title: ECR Repository
        url: http://localhost:4566/
      - title: ArgoCD Applications
        url: http://localhost:8080/applications