apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-controller
  namespace: idp-platform
  labels:
    app: instance-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-controller
  template:
    metadata:
      labels:
        app: instance-controller
    spec:
      serviceAccountName: instance-controller
      containers:
      - name: controller
        image: idp/instance-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "instance-controller"
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: webhook-certs
          mountPath: /tmp/k8s-webhook-server/serving-certs
          readOnly: true
        - name: multi-instance-config
          mountPath: /config
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: instance-controller-webhook-certs
      - name: multi-instance-config
        configMap:
          name: multi-instance-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-controller
  namespace: idp-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-controller
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - configmaps
  - services
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.idp.io
  resources:
  - idpinstances
  - instancepromotions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - workflows
  - workflowtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - gateways
  - destinationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  - secretstores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instance-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instance-controller
subjects:
- kind: ServiceAccount
  name: instance-controller
  namespace: idp-platform
---
apiVersion: v1
kind: Service
metadata:
  name: instance-controller-webhook
  namespace: idp-platform
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8443
  selector:
    app: instance-controller
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionWebhook
metadata:
  name: instance-controller-webhook
webhooks:
- name: validate.idpinstances.platform.idp.io
  clientConfig:
    service:
      name: instance-controller-webhook
      namespace: idp-platform
      path: /validate-idpinstance
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["platform.idp.io"]
    apiVersions: ["v1"]
    resources: ["idpinstances"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail
- name: validate.instancepromotions.platform.idp.io
  clientConfig:
    service:
      name: instance-controller-webhook
      namespace: idp-platform
      path: /validate-instancepromotion
  rules:
  - operations: ["CREATE", "UPDATE"]
    apiGroups: ["platform.idp.io"]
    apiVersions: ["v1"]
    resources: ["instancepromotions"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail